apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-operator

resources:
  - base/minio-operator.yaml

images:
- name: minio/k8s-operator
  newName: minio/k8s-operator
  newTag: 2.0.2