apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-operator

resources:
  - upstream

images:
  - name: minio/k8s-operator
    newName: minio/k8s-operator
    newTag: v3.0.19
