apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
  - minio-operator.yaml
  - namespace.yaml

images:
- name: minio/k8s-operator
  newName: minio/k8s-operator
  newTag: 2.0.2