apiVersion: v1
kind: Service
metadata:
  name: mattermost-operator-service # Please do not change this value
  labels:
    name: mattermost-operator
  namespace: mattermost-operator
spec:
  type: ClusterIP
  ports:
    - port: 4222
      name: http
    - port: 4233
      name: https
  selector:
    name: mattermost-operator
